module.exports = {

    GROUP_EDIT: "GROUP_EDIT",
    GROUP_DELETE: "GROUP_DELETE",
    MEMBER_ADD: "MEMBER_ADD",
    MEMBER_REMOVE: "MEMBER_REMOVE",
    MEMBER_ROLE_UPDATE: "MEMBER_ROLE_UPDATE",

    EXPENSE_CREATE: "EXPENSE_CREATE",
    EXPENSE_EDIT: "EXPENSE_EDIT",
    EXPENSE_DELETE: "EXPENSE_DELETE",

    SETTLEMENT_CREATE: "SETTLEMENT_CREATE"
};