spring.application.name=main
server.port=8888

spring.datasource.url=jdbc:postgresql://localhost:5432/finapp
spring.datasource.username=janakaran
spring.datasource.password=janakaran

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.security.user.name=finapp
spring.security.user.password=finapp

jwt.secret=FinAppSecretKeyForJwtAuthentication2026FinAppSecureKey
jwt.expiration=86400000